name: learn_app
description: "Note Vatika - Your Garden of Knowledge"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  http: ^1.2.0
  google_mobile_ads: ^5.1.0
  url_launcher: ^6.2.5
  shimmer: ^3.0.0
  flutter_highlight: ^0.7.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/default/logo.jpg"
  adaptive_icon_background: "#1B4332"
  adaptive_icon_foreground: "assets/default/logo.jpg"

flutter:
  uses-material-design: true

  assets:
    - assets/default/
    - lib/temp_data/
